### ISSUE TITLE
possible typo  ".is_68020_or_68020_cpu"

### ISSUE THREAD

**Issue by rollefko** [dplanitzer/Apollo#1]
https://github.com/dplanitzer/Apollo/blob/410111e99ca101fa45e9e49d3e1a6a88edb52c11/Kernel/Sources/cpu_asm.s#L77
https://github.com/dplanitzer/Apollo/blob/410111e99ca101fa45e9e49d3e1a6a88edb52c11/Kernel/Sources/cpu_asm.s#L113

".is_68020_or_68030_cpu"  instead of  ".is_68020_or_68020_cpu"

**Comment by dplanitzer** [comment]
Hi rollefko, you're right. I fixed the spelling.
